import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P } from "next/font/google";

import { Navbar } from "@/components/Navbar";
import { WalletConnectProvider } from "@/components/WalletConnect";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pixel = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div
          className={`${pixel.className} flex min-h-screen flex-col bg-[var(--pf-bg)] text-[var(--pf-text)]`}
        >
          <WalletConnectProvider>
            <Navbar />
            {children}
          </WalletConnectProvider>
        </div>
      </body>
    </html>
  );
}
